version: '3.8'
services:
  frontend:
    build:
      context: ./frontend/
    container_name: fs-frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URI=http://backend:8000/
  backend:
    build:
      context: ./backend/
    container_name: fs-backend
    restart: unless-stopped
    environment:
      - PORT=8000
      - METRICS_SERVER_PORT=9100
      - MONGO_URI=mongodb+srv://mrsmithz:123456Za@cluster0.fydss.mongodb.net/fullstack-dev
      - NODE_ENV=prd
    ports:
      - 8000:8000
      - 9100:9100
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - 9999:3000
    volumes:
      - ./config/datasources:/etc/grafana/provisioning/datasources
  zipkin:
    image: openzipkin/zipkin
    restart: unless-stopped
    ports:
      - 9411:9411